/* Auto-generated by overlay-dev-setup.ts
   Source: overlayMap.json
   Do not edit manually — commit overlayMap.ts instead. */
export const overlayMap = {
  "global": {
    "globalFtcoLoader1": {
      "id": "aa95f51993",
      "component": "GlobalFtcoLoader1",
      "props": {},
      "editable": true
    },
    "globalFtcoLoader2": {
      "id": "5d9f655b34",
      "component": "GlobalFtcoLoader2",
      "props": {
        "text": [],
        "links": [],
        "images": [],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "globalWrap0": {
      "id": "0581a21dab",
      "component": "GlobalWrap0",
      "props": {
        "text": [
          {
            "value": "+00 1234 567",
            "tag": "a"
          },
          {
            "value": "youremail@email.com",
            "tag": "a"
          },
          {
            "value": "Facebook",
            "tag": "i"
          },
          {
            "value": "Twitter",
            "tag": "i"
          },
          {
            "value": "Instagram",
            "tag": "i"
          },
          {
            "value": "Dribbble",
            "tag": "i"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "+00 1234 567"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "youremail@email.com"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Facebook"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Twitter"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Instagram"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Dribbble"
          }
        ],
        "images": [],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "mapWrap": {
      "id": "62b48f9446",
      "component": "MapWrap",
      "props": {},
      "editable": true
    },
    "globalHeroWrap1": {
      "id": "673d209079",
      "component": "GlobalHeroWrap1",
      "props": {
        "text": [
          {
            "value": "Professional",
            "tag": "h1"
          },
          {
            "value": "Pressure",
            "tag": "span"
          },
          {
            "value": "Washing",
            "tag": "span"
          },
          {
            "value": "Services",
            "tag": "h1"
          },
          {
            "value": "Learn more",
            "tag": "a"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Learn more"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_1.jpg"
          }
        ]
      },
      "editable": true
    },
    "navbar": {
      "id": "2f1f8fd033",
      "component": "Navbar",
      "props": {
        "text": [
          {
            "value": "Pressure",
            "tag": "a"
          },
          {
            "value": "",
            "tag": "span"
          },
          {
            "value": "Menu",
            "tag": "button"
          },
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "About",
            "tag": "a"
          },
          {
            "value": "Services",
            "tag": "a"
          },
          {
            "value": "Gallery",
            "tag": "a"
          },
          {
            "value": "Blog",
            "tag": "a"
          },
          {
            "value": "Contact",
            "tag": "a"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "/",
            "text": "Pressure Washing"
          },
          {
            "tag": "a",
            "href": "/",
            "text": "Home"
          },
          {
            "tag": "a",
            "href": "/about",
            "text": "About"
          },
          {
            "tag": "a",
            "href": "/services",
            "text": "Services"
          },
          {
            "tag": "a",
            "href": "/gallery",
            "text": "Gallery"
          },
          {
            "tag": "a",
            "href": "/blog",
            "text": "Blog"
          },
          {
            "tag": "a",
            "href": "/contact",
            "text": "Contact"
          }
        ],
        "images": [],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "footer": {
      "id": "8234f0a11d",
      "component": "Footer",
      "props": {
        "text": [
          {
            "value": "Pressure Washing",
            "tag": "h2"
          },
          {
            "value": "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
            "tag": "p"
          },
          {
            "value": "Latest News",
            "tag": "h2"
          },
          {
            "value": "Even the all-powerful Pointing has no control about",
            "tag": "h3"
          },
          {
            "value": "Jun 14, 2020",
            "tag": "div"
          },
          {
            "value": "Admin",
            "tag": "div"
          },
          {
            "value": "19",
            "tag": "div"
          },
          {
            "value": "Even the all-powerful Pointing has no control about",
            "tag": "h3"
          },
          {
            "value": "Jun 14, 2020",
            "tag": "div"
          },
          {
            "value": "Admin",
            "tag": "div"
          },
          {
            "value": "19",
            "tag": "div"
          },
          {
            "value": "Quick Links",
            "tag": "h2"
          },
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "About",
            "tag": "a"
          },
          {
            "value": "Services",
            "tag": "a"
          },
          {
            "value": "Works",
            "tag": "a"
          },
          {
            "value": "Blog",
            "tag": "a"
          },
          {
            "value": "Contact",
            "tag": "a"
          },
          {
            "value": "Have a Questions?",
            "tag": "h2"
          },
          {
            "value": "203 Fake St. Mountain View, San Francisco, California, USA",
            "tag": "span"
          },
          {
            "value": "+2 392 3929 210",
            "tag": "span"
          },
          {
            "value": "info@yourdomain.com",
            "tag": "span"
          },
          {
            "value": "© ",
            "tag": "p"
          },
          {
            "value": " Crafted with passion ",
            "tag": "p"
          },
          {
            "value": " on ",
            "tag": "p"
          },
          {
            "value": " — Empowering creators to launch beautiful sites in minutes.",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Jun 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "19"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Jun 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "19"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Home"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "About"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Services"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Works"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Blog"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Contact"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "+2 392 3929 210"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "info@yourdomain.com"
          },
          {
            "tag": "a",
            "href": "https://budoboost.ai",
            "text": "BudoBoost.ai"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          }
        ],
        "variables": [
          {
            "expr": "{currentYear}"
          }
        ],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/blog": {
    "sec0": {
      "id": "e01f368e5f",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "Blog",
            "tag": "span"
          },
          {
            "value": "Our Blog",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "index.html",
            "text": "Home"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "d317b1a023",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "<",
            "tag": "a"
          },
          {
            "value": "2",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "4",
            "tag": "a"
          },
          {
            "value": "5",
            "tag": "a"
          },
          {
            "value": ">",
            "tag": "a"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "<"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "2"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "4"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "5"
          },
          {
            "tag": "a",
            "href": "#",
            "text": ">"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_5.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_6.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_5.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_6.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/about": {
    "sec2": {
      "id": "987629ac72",
      "component": "Sec2",
      "props": {
        "text": [
          {
            "value": "We Provide Free Quotation",
            "tag": "h2"
          },
          {
            "value": "Free Consultation",
            "tag": "a"
          },
          {
            "value": "Customer",
            "tag": "span"
          },
          {
            "value": "Professionals",
            "tag": "span"
          },
          {
            "value": "Products",
            "tag": "span"
          },
          {
            "value": "Pets Hosted",
            "tag": "span"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Free Consultation"
          }
        ],
        "images": [],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "ddb18ed3a2",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "Welcome Pressure Washing",
            "tag": "h2"
          },
          {
            "value": "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.",
            "tag": "p"
          },
          {
            "value": "50 Years of Service",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Professional & Experienced Staff",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "High Quality & Reliable Service",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Customer Service & Expert Advice",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          }
        ],
        "links": [],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/about-1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec0": {
      "id": "9c83d4da46",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "About us",
            "tag": "span"
          },
          {
            "value": "About Us",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "index.html",
            "text": "Home"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ]
      },
      "editable": true
    },
    "sec3": {
      "id": "9c6b271c03",
      "component": "Sec3",
      "props": {
        "text": [
          {
            "value": "Happy Clients & Feedbacks",
            "tag": "h2"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Racky Henderson",
            "tag": "p"
          },
          {
            "value": "Father",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Henry Dee",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Mark Huff",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Rodel Golez",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Ken Bosh",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          }
        ],
        "links": [],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/blog-single": {
    "sec0": {
      "id": "8148b6ab69",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "Blog",
            "tag": "a"
          },
          {
            "value": "Blog Single",
            "tag": "span"
          },
          {
            "value": "Blog Details",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "index.html",
            "text": "Home"
          },
          {
            "tag": "a",
            "href": "blog.html",
            "text": "Blog"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec1Part1": {
      "id": "13ebed8d0e",
      "component": "Sec1Part1",
      "props": {
        "text": [
          {
            "value": "It is a long established fact a reader be distracted",
            "tag": "h2"
          },
          {
            "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, eius mollitia suscipit, quisquam doloremque distinctio perferendis et doloribus unde architecto optio laboriosam porro adipisci sapiente officiis nemo accusamus ad praesentium? Esse minima nisi et. Dolore perferendis, enim praesentium omnis, iste doloremque quia officia optio deserunt molestiae voluptates soluta architecto tempora.",
            "tag": "p"
          },
          {
            "value": "Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!",
            "tag": "p"
          },
          {
            "value": "#2. Creative WordPress Themes",
            "tag": "h2"
          },
          {
            "value": "Temporibus ad error suscipit exercitationem hic molestiae totam obcaecati rerum, eius aut, in. Exercitationem atque quidem tempora maiores ex architecto voluptatum aut officia doloremque. Error dolore voluptas, omnis molestias odio dignissimos culpa ex earum nisi consequatur quos odit quasi repellat qui officiis reiciendis incidunt hic non? Debitis commodi aut, adipisci.",
            "tag": "p"
          },
          {
            "value": "Quisquam esse aliquam fuga distinctio, quidem delectus veritatis reiciendis. Nihil explicabo quod, est eos ipsum. Unde aut non tenetur tempore, nisi culpa voluptate maiores officiis quis vel ab consectetur suscipit veritatis nulla quos quia aspernatur perferendis, libero sint. Error, velit, porro. Deserunt minus, quibusdam iste enim veniam, modi rem maiores.",
            "tag": "p"
          },
          {
            "value": "Odit voluptatibus, eveniet vel nihil cum ullam dolores laborum, quo velit commodi rerum eum quidem pariatur! Quia fuga iste tenetur, ipsa vel nisi in dolorum consequatur, veritatis porro explicabo soluta commodi libero voluptatem similique id quidem? Blanditiis voluptates aperiam non magni. Reprehenderit nobis odit inventore, quia laboriosam harum excepturi ea.",
            "tag": "p"
          },
          {
            "value": "Adipisci vero culpa, eius nobis soluta. Dolore, maxime ullam ipsam quidem, dolor distinctio similique asperiores voluptas enim, exercitationem ratione aut adipisci modi quod quibusdam iusto, voluptates beatae iure nemo itaque laborum. Consequuntur et pariatur totam fuga eligendi vero dolorum provident. Voluptatibus, veritatis. Beatae numquam nam ab voluptatibus culpa, tenetur recusandae!",
            "tag": "p"
          },
          {
            "value": "Voluptas dolores dignissimos dolorum temporibus, autem aliquam ducimus at officia adipisci quasi nemo a perspiciatis provident magni laboriosam repudiandae iure iusto commodi debitis est blanditiis alias laborum sint dolore. Dolores, iure, reprehenderit. Error provident, pariatur cupiditate soluta doloremque aut ratione. Harum voluptates mollitia illo minus praesentium, rerum ipsa debitis, inventore?",
            "tag": "p"
          },
          {
            "value": "George Washington",
            "tag": "h3"
          },
          {
            "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!",
            "tag": "p"
          },
          {
            "value": "6 Comments",
            "tag": "h3"
          },
          {
            "value": "John Doe",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020 at 10:05pm",
            "tag": "div"
          },
          {
            "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?",
            "tag": "p"
          },
          {
            "value": "Reply",
            "tag": "a"
          },
          {
            "value": "Leave a comment",
            "tag": "h3"
          },
          {
            "value": "Name *",
            "tag": "label"
          },
          {
            "value": "Email *",
            "tag": "label"
          },
          {
            "value": "Website",
            "tag": "label"
          },
          {
            "value": "Message",
            "tag": "label"
          },
          {
            "value": "Services",
            "tag": "h3"
          },
          {
            "value": "House Cleaning",
            "tag": "a"
          },
          {
            "value": "Roof Cleaning",
            "tag": "a"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "a"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "a"
          },
          {
            "value": "Patio Cleaning",
            "tag": "a"
          },
          {
            "value": "Building Cleaning",
            "tag": "a"
          },
          {
            "value": "Concrete Cleaning",
            "tag": "a"
          },
          {
            "value": "Sidewalk Cleaning",
            "tag": "a"
          },
          {
            "value": "Recent Blog",
            "tag": "h3"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "a"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "19",
            "tag": "a"
          },
          {
            "value": "Tag Cloud",
            "tag": "h3"
          },
          {
            "value": "house",
            "tag": "a"
          },
          {
            "value": "clean",
            "tag": "a"
          },
          {
            "value": "washing",
            "tag": "a"
          },
          {
            "value": "wash",
            "tag": "a"
          },
          {
            "value": "pressure",
            "tag": "a"
          },
          {
            "value": "machine",
            "tag": "a"
          },
          {
            "value": "roof",
            "tag": "a"
          },
          {
            "value": "Paragraph",
            "tag": "h3"
          },
          {
            "value": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Life"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Sport"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Tech"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Travel"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Reply"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "House Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Driveway Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Gutter Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Building Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Concrete Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Sidewalk Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "19"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "house"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "clean"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "washing"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "wash"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "pressure"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "machine"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "roof"
          }
        ],
        "images": [
          {
            "tag": "img",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg",
            "alt": "",
            "title": ""
          },
          {
            "tag": "img",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg",
            "alt": "",
            "title": ""
          },
          {
            "tag": "img",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg",
            "alt": "Image placeholder",
            "title": ""
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/contact": {
    "sec0": {
      "id": "8b497f34cd",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "Contact",
            "tag": "span"
          },
          {
            "value": "Contact",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "index.html",
            "text": "Home"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "6f5c4c7464",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "Address:",
            "tag": "span"
          },
          {
            "value": "198 West 21th Street, Suite 721 New York NY 10016",
            "tag": "p"
          },
          {
            "value": "Phone:",
            "tag": "span"
          },
          {
            "value": "+ 1235 2355 98",
            "tag": "a"
          },
          {
            "value": "Email:",
            "tag": "span"
          },
          {
            "value": "info@yoursite.com",
            "tag": "a"
          },
          {
            "value": "Website",
            "tag": "span"
          },
          {
            "value": "yoursite.com",
            "tag": "a"
          },
          {
            "value": "Contact Us",
            "tag": "h3"
          },
          {
            "value": "Full Name",
            "tag": "label"
          },
          {
            "value": "Email Address",
            "tag": "label"
          },
          {
            "value": "Subject",
            "tag": "label"
          },
          {
            "value": "Message",
            "tag": "label"
          },
          {
            "value": "Send Message",
            "tag": "input"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "tel://1234567920",
            "text": "+ 1235 2355 98"
          },
          {
            "tag": "a",
            "href": "mailto:info@yoursite.com",
            "text": "info@yoursite.com"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "yoursite.com"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/about-1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/gallery": {
    "sec0": {
      "id": "5154c4f856",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "Gallery",
            "tag": "span"
          },
          {
            "value": "Our gallery",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "index.html",
            "text": "Home"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "91e9555e75",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "Roof cleaning",
            "tag": "span"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h2"
          },
          {
            "value": "Driveway",
            "tag": "span"
          },
          {
            "value": "Gaston Driveway",
            "tag": "h2"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "span"
          },
          {
            "value": "Gutter",
            "tag": "h2"
          },
          {
            "value": "Patio Cleaning",
            "tag": "span"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h2"
          },
          {
            "value": "Building Cleaning",
            "tag": "span"
          },
          {
            "value": "Building Cleaning",
            "tag": "h2"
          },
          {
            "value": "Building Cleaning",
            "tag": "span"
          },
          {
            "value": "Hall Way",
            "tag": "h2"
          },
          {
            "value": "Patio Cleaning",
            "tag": "span"
          },
          {
            "value": "Garden Cleaning",
            "tag": "h2"
          },
          {
            "value": "Office",
            "tag": "span"
          },
          {
            "value": "Office Cleaning",
            "tag": "h2"
          },
          {
            "value": "1",
            "tag": "span"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-1.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-2.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Gaston Driveway"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-3.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Gutter"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-4.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-5.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Building Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-6.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Hall Way"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-7.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Garden Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-8.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Office Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "<"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "2"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "4"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "5"
          },
          {
            "tag": "a",
            "href": "#",
            "text": ">"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-5.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-6.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-7.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-8.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/home": {
    "sec0": {
      "id": "73502c14b3",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Why Choose Us?",
            "tag": "h2"
          },
          {
            "value": "50 Years of Service",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Professional & Experienced Staff",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "High Quality & Reliable Service",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Customer Service & Expert Advice",
            "tag": "h4"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          }
        ],
        "links": [],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/about-1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/about-1.jpg"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "63e98d6f57",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "We Provide Free Quotation",
            "tag": "h2"
          },
          {
            "value": "Free Consultation",
            "tag": "a"
          },
          {
            "value": "Customer",
            "tag": "span"
          },
          {
            "value": "Professionals",
            "tag": "span"
          },
          {
            "value": "Products",
            "tag": "span"
          },
          {
            "value": "Pets Hosted",
            "tag": "span"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Free Consultation"
          }
        ],
        "images": [],
        "variables": [],
        "assets": []
      },
      "editable": true
    },
    "sec2": {
      "id": "7db7029c6c",
      "component": "Sec2",
      "props": {
        "text": [
          {
            "value": "Pressure Washing Services",
            "tag": "h2"
          },
          {
            "value": "House Washing",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Building Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Concrete Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Sidewalk Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec6": {
      "id": "f8af2f3054",
      "component": "Sec6",
      "props": {
        "text": [
          {
            "value": "Latest news from our blog",
            "tag": "h2"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          },
          {
            "value": "June 14, 2020",
            "tag": "a"
          },
          {
            "value": "Admin",
            "tag": "a"
          },
          {
            "value": "3",
            "tag": "a"
          },
          {
            "value": "Even the all-powerful Pointing has no control about the blind texts",
            "tag": "h3"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          },
          {
            "tag": "a",
            "href": "blog-single.html",
            "text": ""
          },
          {
            "tag": "a",
            "href": "#",
            "text": "June 14, 2020"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Admin"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "3"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Even the all-powerful Pointing has no control about the blind texts"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/image_3.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec7": {
      "id": "5fb2d2975b",
      "component": "Sec7",
      "props": {
        "text": [
          {
            "value": "Free Consultation",
            "tag": "h2"
          },
          {
            "value": "Select services",
            "tag": "option"
          },
          {
            "value": "House Washing",
            "tag": "option"
          },
          {
            "value": "Roof Cleaning",
            "tag": "option"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "option"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "option"
          },
          {
            "value": "Patio Cleaning",
            "tag": "option"
          },
          {
            "value": "Building Cleaning",
            "tag": "option"
          },
          {
            "value": "Concrete Cleaning",
            "tag": "option"
          },
          {
            "value": "Sidewal Cleaning",
            "tag": "option"
          },
          {
            "value": "Send message",
            "tag": "input"
          }
        ],
        "links": [],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_3.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_3.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec4": {
      "id": "8f52af651e",
      "component": "Sec4",
      "props": {
        "text": [
          {
            "value": "Happy Clients & Feedbacks",
            "tag": "h2"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Racky Henderson",
            "tag": "p"
          },
          {
            "value": "Father",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Henry Dee",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Mark Huff",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Rodel Golez",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia",
            "tag": "p"
          },
          {
            "value": "Ken Bosh",
            "tag": "p"
          },
          {
            "value": "Businesswoman",
            "tag": "span"
          }
        ],
        "links": [],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/person_1.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec3": {
      "id": "daced21885",
      "component": "Sec3",
      "props": {
        "text": [
          {
            "value": "Before & After Services",
            "tag": "h2"
          },
          {
            "value": "House Washing",
            "tag": "a"
          },
          {
            "value": "Roof Cleaning",
            "tag": "a"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "a"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "a"
          },
          {
            "value": "Patio Cleaning",
            "tag": "a"
          },
          {
            "value": "Building Cleaning",
            "tag": "a"
          },
          {
            "value": "House Washing",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Building Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#services-1",
            "text": "House Washing"
          },
          {
            "tag": "a",
            "href": "#services-2",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-3",
            "text": "Driveway Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-4",
            "text": "Gutter Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-5",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-6",
            "text": "Building Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "House Washing"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Driveway Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Gutter Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Building Cleaning"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-5.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-6.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-5.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-6.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec5": {
      "id": "d1f85b5d20",
      "component": "Sec5",
      "props": {
        "text": [
          {
            "value": "Roof cleaning",
            "tag": "span"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h2"
          },
          {
            "value": "Driveway",
            "tag": "span"
          },
          {
            "value": "Gaston Driveway",
            "tag": "h2"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "span"
          },
          {
            "value": "Gutter",
            "tag": "h2"
          },
          {
            "value": "Patio Cleaning",
            "tag": "span"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h2"
          },
          {
            "value": "Building Cleaning",
            "tag": "span"
          },
          {
            "value": "Building Cleaning",
            "tag": "h2"
          },
          {
            "value": "Building Cleaning",
            "tag": "span"
          },
          {
            "value": "Hall Way",
            "tag": "h2"
          },
          {
            "value": "Patio Cleaning",
            "tag": "span"
          },
          {
            "value": "Garden Cleaning",
            "tag": "h2"
          },
          {
            "value": "Office",
            "tag": "span"
          },
          {
            "value": "Office Cleaning",
            "tag": "h2"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-1.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-2.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Gaston Driveway"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-3.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Gutter"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-4.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-5.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Building Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-6.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Hall Way"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-7.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Garden Cleaning"
          },
          {
            "tag": "a",
            "href": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-8.jpg",
            "text": ""
          },
          {
            "tag": "a",
            "href": "work-single.html",
            "text": "Office Cleaning"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-5.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-6.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-7.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-8.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-5.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-6.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-7.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/gallery-8.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  },
  "/services": {
    "sec0": {
      "id": "181183e3d9",
      "component": "Sec0",
      "props": {
        "text": [
          {
            "value": "Home",
            "tag": "a"
          },
          {
            "value": "Services",
            "tag": "span"
          },
          {
            "value": "Pressure Washing Servicess",
            "tag": "h1"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "/",
            "text": "Home"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/bg_2.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec1": {
      "id": "66a390e0fd",
      "component": "Sec1",
      "props": {
        "text": [
          {
            "value": "Pressure Washing Services",
            "tag": "h2"
          },
          {
            "value": "House Washing",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Building Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Concrete Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          },
          {
            "value": "Sidewalk Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries.",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Read more"
          }
        ],
        "images": [],
        "variables": [],
        "assets": [
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    },
    "sec2": {
      "id": "2332da3cb5",
      "component": "Sec2",
      "props": {
        "text": [
          {
            "value": "Before & After Services",
            "tag": "h2"
          },
          {
            "value": "House Washing",
            "tag": "a"
          },
          {
            "value": "Roof Cleaning",
            "tag": "a"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "a"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "a"
          },
          {
            "value": "Patio Cleaning",
            "tag": "a"
          },
          {
            "value": "Building Cleaning",
            "tag": "a"
          },
          {
            "value": "House Washing",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Roof Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Driveway Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Gutter Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Patio Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          },
          {
            "value": "Building Cleaning",
            "tag": "h3"
          },
          {
            "value": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.",
            "tag": "p"
          }
        ],
        "links": [
          {
            "tag": "a",
            "href": "#services-1",
            "text": "House Washing"
          },
          {
            "tag": "a",
            "href": "#services-2",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-3",
            "text": "Driveway Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-4",
            "text": "Gutter Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-5",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "#services-6",
            "text": "Building Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "House Washing"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Roof Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Driveway Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Gutter Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Patio Cleaning"
          },
          {
            "tag": "a",
            "href": "#",
            "text": "Building Cleaning"
          }
        ],
        "images": [
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-1.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-2.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-3.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-4.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-5.jpg"
          },
          {
            "tag": "style.backgroundImage",
            "src": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-6.jpg"
          }
        ],
        "variables": [],
        "assets": [
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-1.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-2.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-3.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-4.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-5.jpg"
          },
          {
            "type": "image",
            "path": "https://storage.googleapis.com/budoapps-5aacf.firebasestorage.app/templates/pressurewashing-3365cccdb5/images/services-6.jpg"
          },
          {
            "type": "file",
            "path": "react"
          }
        ]
      },
      "editable": true
    }
  }
} as const;
export type OverlayMap = typeof overlayMap;
